[tox]
envlist = py312, quality
requires = tox-uv>=1

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    pylint --rcfile=pylintrc --exit-zero --disable=no-member,django-not-configured mockprock
    isort --check-only --diff mockprock

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
commands = pytest {posargs}
