# Check that uv.lock is up to date

name: Lockfile Version check

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lockfile-check:
    name: Check uv.lock is up to date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1

      - name: Verify uv.lock is up to date
        run: SETUPTOOLS_SCM_PRETEND_VERSION=0.0.0 uv lock --check
